#!/usr/bin/env bash

set -u
set -e

maxmessages=10

foo=$(mail < /dev/null | head -n1 | awk '{print  $2}')
echo "Ciunt: $foo"

if [ $foo -gt $maxmessages ]; then
	let max=$foo-$maxmessages
	echo "d1-$max" | mail > /dev/null
else
	echo "nothing to do"
fi

foo=$(mail < /dev/null | head -n1 | awk '{print  $2}')
echo "Ciunt: $foo"
